language: node_js # will use nvmrc by default
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.0
  - export PATH=$HOME/.yarn/bin:$PATH
branches:
  only:
    - master
    - feat/v4-for-real-now
sudo: false # container based infra
script: 
  - yarn test:ci
cache:
  yarn: true
  directories:
    - node_modules
